# Example of Docker image of NodeJS
FROM debian:12

ENV TZ=Europe/Paris

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
RUN apt-get install -y nodejs

# Libs for Canvas
RUN apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
# Libs for Puppeteer
RUN apt-get install -y libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

RUN useradd -d /home/server -u 1000 server
USER server
