# Example of Docker image of NodeJS
FROM debian:11

ENV TZ=Europe/Paris

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash -
RUN apt-get install -y nodejs

# Libs for Canvas
RUN apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

RUN useradd -d /home/server -u 1000 server
USER server
WORKDIR /home/server
